{
 "title": "Minecraft Player Statistic",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server_name",
    "label": "Server Name",
    "query": "label_values(mc_player_online, server_name)"
   },
   {
    "name": "player",
    "label": "Player",
    "query": "label_values(mc_player_online, name)"
   },
   { "name": "ticks_per_second", "label": "Ticks per second", "query": "20" }
  ]
 },
 "panels": [
  {
   "title": "Players Online",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "expr": "mc_player_online{server_name=~\"$server_name\",name=~\"$player\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Animals Bred",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Animals Bred over time",
     "type": "timeseries",
     "description": "The number of times the player bred two mobs. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"ANIMALS_BRED\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Animals Bred by player",
     "type": "piechart",
     "description": "The number of times the player bred two mobs. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"ANIMALS_BRED\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Barrels Opened",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Barrels Opened over time",
     "type": "timeseries",
     "description": "The number of times the player has opened a Barrel. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"OPEN_BARREL\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Barrels Opened by player",
     "type": "piechart",
     "description": "The number of times the player has opened a Barrel. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"OPEN_BARREL\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Bells Rung",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Bells Rung over time",
     "type": "timeseries",
     "description": "The number of times the player has rung a Bell. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"BELL_RING\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Bells Rung by player",
     "type": "piechart",
     "description": "The number of times the player has rung a Bell. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"BELL_RING\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Damage Blocked By Shield",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Damage Blocked By Shield over time",
     "type": "timeseries",
     "description": "The amount of damage the player has blocked with a shield in tenths of 1♥. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"DAMAGE_BLOCKED_BY_SHIELD\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Damage Blocked By Shield by player",
     "type": "piechart",
     "description": "The amount of damage the player has blocked with a shield in tenths of 1♥. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"DAMAGE_BLOCKED_BY_SHIELD\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Damage Dealt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Damage Dealt over time",
     "type": "timeseries",
     "description": "The amount of damage the player has dealt in tenths of 1♥. Includes only melee attacks. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"DAMAGE_DEALT\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Damage Dealt by player",
     "type": "piechart",
     "description": "The amount of damage the player has dealt in tenths of 1♥. Includes only melee attacks. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"DAMAGE_DEALT\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Damage Resisted",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Damage Resisted over time",
     "type": "timeseries",
     "description": "The amount of damage the player has resisted in tenths of 1♥. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"DAMAGE_RESISTED\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Damage Resisted by player",
     "type": "piechart",
     "description": "The amount of damage the player has resisted in tenths of 1♥. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"DAMAGE_RESISTED\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Damage Taken",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Damage Taken over time",
     "type": "timeseries",
     "description": "The amount of damage the player has taken in tenths of 1♥. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"DAMAGE_TAKEN\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Damage Taken by player",
     "type": "piechart",
     "description": "The amount of damage the player has taken in tenths of 1♥. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"DAMAGE_TAKEN\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance by Boat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance by Boat over time",
     "type": "timeseries",
     "description": "The total distance traveled by boats. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"BOAT_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance by Boat by player",
     "type": "piechart",
     "description": "The total distance traveled by boats. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"BOAT_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance by Elytra",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance by Elytra over time",
     "type": "timeseries",
     "description": "The total distance traveled by elytra. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"AVIATE_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance by Elytra by player",
     "type": "piechart",
     "description": "The total distance traveled by elytra. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"AVIATE_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance by Horse",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance by Horse over time",
     "type": "timeseries",
     "description": "The total distance traveled by horses. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"HORSE_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance by Horse by player",
     "type": "piechart",
     "description": "The total distance traveled by horses. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"HORSE_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance by Minecart",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance by Minecart over time",
     "type": "timeseries",
     "description": "The total distance traveled by minecarts. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"MINECART_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance by Minecart by player",
     "type": "piechart",
     "description": "The total distance traveled by minecarts. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"MINECART_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Climbed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Climbed over time",
     "type": "timeseries",
     "description": "The total distance traveled up ladders or vines.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"CLIMB_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Climbed by player",
     "type": "piechart",
     "description": "The total distance traveled up ladders or vines.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"CLIMB_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Crouched",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Crouched over time",
     "type": "timeseries",
     "description": "The total distance walked while sneaking. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"CROUCH_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Crouched by player",
     "type": "piechart",
     "description": "The total distance walked while sneaking. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"CROUCH_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Fallen",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Fallen over time",
     "type": "timeseries",
     "description": "The total distance fallen, excluding jumping. If the player falls more than one block, the entire jump is counted. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"FALL_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Fallen by player",
     "type": "piechart",
     "description": "The total distance fallen, excluding jumping. If the player falls more than one block, the entire jump is counted. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"FALL_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Flown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Flown over time",
     "type": "timeseries",
     "description": "Distance traveled upward and forward at the same time, while more than one block above the ground. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"FLY_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Flown by player",
     "type": "piechart",
     "description": "Distance traveled upward and forward at the same time, while more than one block above the ground. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"FLY_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Fish Caught",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fish Caught over time",
     "type": "timeseries",
     "description": "The number of fish caught. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"FISH_CAUGHT\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Fish Caught by player",
     "type": "piechart",
     "description": "The number of fish caught. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"FISH_CAUGHT\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Games Quit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Games Quit over time",
     "type": "timeseries",
     "description": "The number of times \"Save and quit to title\" has been clicked. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"LEAVE_GAME\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Games Quit by player",
     "type": "piechart",
     "description": "The number of times \"Save and quit to title\" has been clicked. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"LEAVE_GAME\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Anvil",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Anvil over time",
     "type": "timeseries",
     "description": "The number of times interacted with anvils. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_ANVIL\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Anvil by player",
     "type": "piechart",
     "description": "The number of times interacted with anvils. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_ANVIL\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Blast Furnace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Blast Furnace over time",
     "type": "timeseries",
     "description": "The number of times interacted with Blast Furnaces. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_BLAST_FURNACE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Blast Furnace by player",
     "type": "piechart",
     "description": "The number of times interacted with Blast Furnaces. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_BLAST_FURNACE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Cartography Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Cartography Table over time",
     "type": "timeseries",
     "description": "The number of times interacted with Cartography Tables. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_CARTOGRAPHY_TABLE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Cartography Table by player",
     "type": "piechart",
     "description": "The number of times interacted with Cartography Tables. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_CARTOGRAPHY_TABLE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Grindstone",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Grindstone over time",
     "type": "timeseries",
     "description": "The number of times interacted with Grindstones. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_GRINDSTONE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Grindstone by player",
     "type": "piechart",
     "description": "The number of times interacted with Grindstones. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_GRINDSTONE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Loom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Loom over time",
     "type": "timeseries",
     "description": "The number of times interacted with Looms. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_LOOM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Loom by player",
     "type": "piechart",
     "description": "The number of times interacted with Looms. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_LOOM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Smithing Table",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Smithing Table over time",
     "type": "timeseries",
     "description": "The number of times interacted with Smithing Tables. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_SMITHING_TABLE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Smithing Table by player",
     "type": "piechart",
     "description": "The number of times interacted with Smithing Tables. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_SMITHING_TABLE\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Smoker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Smoker over time",
     "type": "timeseries",
     "description": "The number of times interacted with Smokers. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_SMOKER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Smoker by player",
     "type": "piechart",
     "description": "The number of times interacted with Smokers. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_SMOKER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Interactions with Stonecutter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Interactions with Stonecutter over time",
     "type": "timeseries",
     "description": "The number of times interacted with Stonecutters. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"INTERACT_WITH_STONECUTTER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Interactions with Stonecutter by player",
     "type": "piechart",
     "description": "The number of times interacted with Stonecutters. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"INTERACT_WITH_STONECUTTER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Items Dropped",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Items Dropped over time",
     "type": "timeseries",
     "description": "The number of items dropped. This does not include items dropped upon death. If a group of items are dropped together, eg a stack of 64, it only counts as 1. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"DROP\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Items Dropped by player",
     "type": "piechart",
     "description": "The number of items dropped. This does not include items dropped upon death. If a group of items are dropped together, eg a stack of 64, it only counts as 1. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"DROP\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Jumps",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jumps over time",
     "type": "timeseries",
     "description": "The total number of jumps performed. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"JUMP\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Jumps by player",
     "type": "piechart",
     "description": "The total number of jumps performed. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"JUMP\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mob Kills",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mob Kills over time",
     "type": "timeseries",
     "description": "The number of mobs the player killed. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"MOB_KILLS\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Mob Kills by player",
     "type": "piechart",
     "description": "The number of mobs the player killed. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"MOB_KILLS\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Number of Deaths",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Deaths over time",
     "type": "timeseries",
     "description": "The number of times the player died.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"DEATHS\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Number of Deaths by player",
     "type": "piechart",
     "description": "The number of times the player died.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"DEATHS\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Player Kills",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Player Kills over time",
     "type": "timeseries",
     "description": "The number of players the player killed (on PvP servers). Indirect kills do not count. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"PLAYER_KILLS\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Player Kills by player",
     "type": "piechart",
     "description": "The number of players the player killed (on PvP servers). Indirect kills do not count. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"PLAYER_KILLS\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raids Triggered",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raids Triggered over time",
     "type": "timeseries",
     "description": "The number of times the player has triggered a Raid. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"RAID_TRIGGER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Raids Triggered by player",
     "type": "piechart",
     "description": "The number of times the player has triggered a Raid. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"RAID_TRIGGER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Raids Won",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Raids Won over time",
     "type": "timeseries",
     "description": "The number of times the player has won a Raid.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"RAID_WIN\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Raids Won by player",
     "type": "piechart",
     "description": "The number of times the player has won a Raid.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"RAID_WIN\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times Slept in a Bed",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Times Slept in a Bed over time",
     "type": "timeseries",
     "description": "The number of times the player has slept in a bed. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"SLEEP_IN_BED\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Times Slept in a Bed by player",
     "type": "piechart",
     "description": "The number of times the player has slept in a bed. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"SLEEP_IN_BED\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Sneak Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Sneak Time over time",
     "type": "timeseries",
     "description": "The time the player has held down the sneak button (tracked in ticks). ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"SNEAK_TIME\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Sneak Time by player",
     "type": "piechart",
     "description": "The time the player has held down the sneak button (tracked in ticks). ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"SNEAK_TIME\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Sprinted",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Sprinted over time",
     "type": "timeseries",
     "description": "The total distance sprinted. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"SPRINT_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Sprinted by player",
     "type": "piechart",
     "description": "The total distance sprinted. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"SPRINT_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance by Strider",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance by Strider over time",
     "type": "timeseries",
     "description": "The total distance traveled by striders via saddles. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"STRIDER_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance by Strider by player",
     "type": "piechart",
     "description": "The total distance traveled by striders via saddles. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"STRIDER_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Swum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Swum over time",
     "type": "timeseries",
     "description": "The total distance covered with sprint-swimming. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"SWIM_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Swum by player",
     "type": "piechart",
     "description": "The total distance covered with sprint-swimming. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"SWIM_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Walked",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Walked over time",
     "type": "timeseries",
     "description": "The total distance walked. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"WALK_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Walked by player",
     "type": "piechart",
     "description": "The total distance walked. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"WALK_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Walked on Water",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Walked on Water over time",
     "type": "timeseries",
     "description": "The distance covered while bobbing up and down over water. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"WALK_ON_WATER_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Walked on Water by player",
     "type": "piechart",
     "description": "The distance covered while bobbing up and down over water. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"WALK_ON_WATER_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Distance Walked under Water",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Distance Walked under Water over time",
     "type": "timeseries",
     "description": "The total distance you have walked underwater.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"WALK_UNDER_WATER_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Distance Walked under Water by player",
     "type": "piechart",
     "description": "The total distance you have walked underwater.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"WALK_UNDER_WATER_ONE_CM\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Talked to Villagers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Talked to Villagers over time",
     "type": "timeseries",
     "description": "The number of times interacted with villagers (opened the trading GUI). ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"TALKED_TO_VILLAGER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Talked to Villagers by player",
     "type": "piechart",
     "description": "The number of times interacted with villagers (opened the trading GUI). ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"TALKED_TO_VILLAGER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Targets Hit",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Targets Hit over time",
     "type": "timeseries",
     "description": "The number of times the player has shot a target block. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"TARGET_HIT\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Targets Hit by player",
     "type": "piechart",
     "description": "The number of times the player has shot a target block. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"TARGET_HIT\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Since Last Death",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Since Last Death over time",
     "type": "timeseries",
     "description": "The time since the player's last death (tracked in ticks). ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"TIME_SINCE_DEATH\", server_name=~\"$server_name\"}) without (player_uid)/$ticks_per_second",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Time Since Last Death by player",
     "type": "piechart",
     "description": "The time since the player's last death (tracked in ticks). ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"TIME_SINCE_DEATH\", server_name=~\"$server_name\"}) without (player_uid)/$ticks_per_second",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Time Since Last Rest",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Since Last Rest over time",
     "type": "timeseries",
     "description": "The time since the player's last rest (tracked in ticks). If this value is greater than 1.00 h, phantoms can spawn. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"TIME_SINCE_REST\", server_name=~\"$server_name\"}) without (player_uid)/$ticks_per_second",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Time Since Last Rest by player",
     "type": "piechart",
     "description": "The time since the player's last rest (tracked in ticks). If this value is greater than 1.00 h, phantoms can spawn. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"TIME_SINCE_REST\", server_name=~\"$server_name\"}) without (player_uid)/$ticks_per_second",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Time with World Open",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time with World Open over time",
     "type": "timeseries",
     "description": "The total amount of time the world was opened (tracked in ticks). Unlike Play Time, if the game is paused this number continues to increase, but it does not change visually while the statistics menu is open. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"TOTAL_WORLD_TIME\", server_name=~\"$server_name\"}) without (player_uid)/$ticks_per_second",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Time with World Open by player",
     "type": "piechart",
     "description": "The total amount of time the world was opened (tracked in ticks). Unlike Play Time, if the game is paused this number continues to increase, but it does not change visually while the statistics menu is open. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"TOTAL_WORLD_TIME\", server_name=~\"$server_name\"}) without (player_uid)/$ticks_per_second",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Traded with Villagers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Traded with Villagers over time",
     "type": "timeseries",
     "description": "The number of times traded with villagers. ",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=~\"TRADED_WITH_VILLAGER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    },
    {
     "title": "Traded with Villagers by player",
     "type": "piechart",
     "description": "The number of times traded with villagers. ",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(mc_player_statistic{player_name=~\"$player\", statistic=\"TRADED_WITH_VILLAGER\", server_name=~\"$server_name\"}) without (player_uid)",
       "legendFormat": "{{player_name}}"
      }
     ]
    }
   ]
  }
 ]
}